### PR TITLE
#4 Options for footer display

### PR DESCRIPTION
**Pull request by remrobem**
#4  

## Description

This pr does not provide any formatting of the footer

Two options available for handling the footer. Need to decide which one to use.

1. Footer sticks to bottom of page, even when content is longer than the viewport
2. Footer is at the bottom of the page at the end of content only. If the content does not fill one page, the footer sticks to the bottom of the page

Look at comments in styles.scss for lines to comment/uncomment to see each option in action.

### CODE REVIEW

**Comment by SchaeStewart** [comment]
@remrobem Can we go with no-sticky footer, but set a min-height on the page content, so that even when the content does not fill the page the user has to scroll.

Maybe we can set the content min-height to `100vh`? Thoughts?

**Comment by remrobem** [comment]
To force a scroll, we would need to use something like min-height: 110vh or 110%. I just tried it and it actually works pretty good. Less than full-page content, have to scroll a little bit to get to footer. More than a page of content, scroll to bottom of content and footer shows up as expected. May need to tweak the vh or % based on the height of the footer. I'll push that up in a minute

**Comment by remrobem** [comment]
There is a change in the pr now to use 105vh - forces scroll when content less that one page

**Comment by SchaeStewart** [comment]
Looks good! I just merged. Thanks!

**Comment by remrobem** [comment]
need to remove some commented code in style.scss once we agree on how we want it to act

**Comment by SchaeStewart** [comment]
@remrobem Sorry, I posted my previous comment and merged before I saw your comment. Re-open or open a new PR if you need to. I liked what I saw with the 105vh though

**Comment by remrobem** [comment]
you got my last change. I was just saying there is commented code that does a fixed sticky footer (always on bottom). Once we are firm on how the footer should behave, we should remove those comments.

**Pull request merged**
